### ISSUE TITLE
pre-existing vm.args isn't honored.

### ISSUE THREAD

**Issue by evanmcc** [basho/cuttlefish#36]
it'd be nice if either file existed that it wouldn't be generated each startup.  as it stands it just looks like app.config is treated that way.

**Comment by jaredmorrow** [comment]
Similarly, if you put an old app.config, but not vm.args file it will crash.  The conditional use of old-style v. cuttlefish is pinned on the existence on the app.config, it should maybe have another level to the case to separate out the vm.args.

**Comment by joedevivo** [comment]
yeah, the heart of the problem is in `case filelib:is_file(app.config)`

I've been going back and forth on the right way to make this choice. Here's where I'm at now:

If both app.config and vm.args exist in platform_etc_dir, skip the fish

If a .conf file is passed into the escript, and it exists, but either (or both) of the app.config and vm.args are missing, generate new vm.args and app.config, but only start riak with the generated version if the legacy one doesn't exist?

make sense? basically, if we're generating one, we're generating both, but we don't have actually use both.

**Comment by jaredmorrow** [comment]
I think if the app.config is present we should always use it, with warnings / messages printed.

**Comment by joedevivo** [comment]
@jaredmorrow yeah, that's what I'm saying, the words just aren't coming out right...

If there's an app.config, use it. If there's a vm.args use it. If either is missing, generate both, but only use the generated one for the one that's missing. If both are missing, use both generated. clearer?

**Comment by jaredmorrow** [comment]
Yes, +1
